apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: alerts
spec:
  serviceAccountName: cluster-metrics-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command:
    - /bin/bash
    - -c
    - "while true; do sleep 3600; done"

