apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: internal-registry.tkg.mobilink.net.pk/wso2-prod/talha/dnsutils:4.0
    #image: tshahab/dnsutils:4.0
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
