apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2-scripts-pvc
  namespace: wso2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: tkg-rwx-policy-prod
  volumeMode: Filesystem
